INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (1, '500');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (2, 'Grande Punto');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (3, 'Punto Evo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (4, '500c');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (5, '695');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (6, 'Punto');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (7, '155');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (8, '156');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (9, '159');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (10, '164');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (11, '145');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (12, '147');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (13, '146');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (14, 'Gtv');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (15, 'Spider');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (16, '166');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (17, 'Gt');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (18, 'Crosswagon');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (19, 'Brera');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (20, '90');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (21, '75');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (22, '33');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (23, 'Giulietta');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (24, 'Sprint');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (25, 'Mito');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (26, 'Expander');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (27, '10');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (28, '24');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (29, 'Dacia');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (30, 'Rocsta');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (31, 'Rocsta');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (32, 'Db7');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (33, 'V8');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (34, 'Db9');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (35, 'Vanquish');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (36, 'V8 Vantage');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (37, 'Vantage');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (38, 'Dbs');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (39, 'Volante');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (40, 'Virage');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (41, 'Vantage V8');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (42, 'Vantage V12');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (43, 'Rapide');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (44, 'Cygnet');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (45, '80');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (46, 'A4');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (47, 'A6');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (48, 'S6');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (49, 'Coupe');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (50, 'S2');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (51, 'Rs2');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (52, 'A8');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (53, 'Cabriolet');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (54, 'S8');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (55, 'A3');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (56, 'S4');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (57, 'Tt');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (58, 'S3');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (59, 'Allroad Quattro');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (60, 'Rs4');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (61, 'A2');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (62, 'Rs6');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (63, 'Q7');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (64, 'R8');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (65, 'A5');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (66, 'S5');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (67, 'V8');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (68, '200');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (69, '100');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (70, '90');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (71, 'Tts');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (72, 'Q5');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (73, 'A4 Allroad Quattro');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (74, 'Tt Rs');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (75, 'Rs5');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (76, 'A1');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (77, 'A7');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (78, 'Rs3');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (79, 'Q3');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (80, 'A6 Allroad Quattro');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (81, 'S7');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (82, 'Sq5');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (83, 'Mini');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (84, 'Montego');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (85, 'Maestro');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (86, 'Metro');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (87, 'Mini Moke');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (88, 'Diesel');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (89, 'Brooklands');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (90, 'Turbo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (91, 'Continental');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (92, 'Azure');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (93, 'Arnage');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (94, 'Continental Gt');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (95, 'Continental Flying Spur');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (96, 'Turbo R');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (97, 'Mulsanne');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (98, 'Eight');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (99, 'Continental Gtc');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (100, 'Continental Supersports');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (101, 'Freeclimber Diesel');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (102, 'Serie 3');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (103, 'Serie 5');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (104, 'Compact');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (105, 'Serie 7');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (106, 'Serie 8');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (107, 'Z3');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (108, 'Z4');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (109, 'Z8');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (110, 'X5');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (111, 'Serie 6');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (112, 'X3');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (113, 'Serie 1');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (114, 'Z1');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (115, 'X6');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (116, 'X1');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (117, 'Seville');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (118, 'Sts');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (119, 'El Dorado');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (120, 'Cts');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (121, 'Xlr');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (122, 'Srx');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (123, 'Escalade');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (124, 'Bls');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (125, 'Corvette');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (126, 'Blazer');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (127, 'Astro');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (128, 'Nubira');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (129, 'Evanda');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (130, 'Trans Sport');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (131, 'Camaro');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (132, 'Matiz');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (133, 'Alero');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (134, 'Tahoe');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (135, 'Tacuma');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (136, 'Trailblazer');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (137, 'Kalos');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (138, 'Aveo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (139, 'Lacetti');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (140, 'Epica');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (141, 'Captiva');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (142, 'Hhr');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (143, 'Cruze');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (144, 'Spark');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (145, 'Orlando');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (146, 'Volt');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (147, 'Malibu');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (148, 'Vision');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (149, '300m');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (150, 'Grand Voyager');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (151, 'Viper');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (152, 'Neon');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (153, 'Voyager');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (154, 'Stratus');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (155, 'Sebring');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (156, 'Sebring 200c');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (157, 'New Yorker');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (158, 'Pt Cruiser');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (159, 'Crossfire');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (160, '300c');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (161, 'Le Baron');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (162, 'Saratoga');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (163, 'Xantia');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (164, 'Xm');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (165, 'Ax');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (166, 'Zx');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (167, 'Evasion');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (168, 'C8');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (169, 'Saxo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (170, 'C2');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (171, 'Xsara');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (172, 'C4');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (173, 'Xsara Picasso');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (174, 'C5');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (175, 'C3');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (176, 'C3 Pluriel');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (177, 'C1');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (178, 'C6');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (179, 'Grand C4 Picasso');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (180, 'C4 Picasso');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (181, 'Ccrosser');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (182, 'C15');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (183, 'Jumper');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (184, 'Jumpy');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (185, 'Berlingo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (186, 'Bx');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (187, 'C25');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (188, 'Cx');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (189, 'Gsa');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (190, 'Visa');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (191, 'Lna');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (192, '2cv');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (193, 'Nemo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (194, 'C4 Sedan');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (195, 'Berlingo First');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (196, 'C3 Picasso');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (197, 'Ds3');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (198, 'Czero');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (199, 'Ds4');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (200, 'Ds5');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (201, 'C4 Aircross');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (202, 'Celysee');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (203, 'Corvette');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (204, 'Contac');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (205, 'Logan');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (206, 'Sandero');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (207, 'Duster');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (208, 'Lodgy');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (209, 'Nexia');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (210, 'Aranos');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (211, 'Lanos');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (212, 'Nubira');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (213, 'Compact');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (214, 'Nubira Compact');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (215, 'Leganza');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (216, 'Evanda');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (217, 'Matiz');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (218, 'Tacuma');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (219, 'Kalos');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (220, 'Lacetti');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (221, 'Applause');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (222, 'Charade');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (223, 'Rocky');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (224, 'Feroza');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (225, 'Terios');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (226, 'Sirion');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (227, 'Serie Xj');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (228, 'Xj');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (229, 'Double Six');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (230, 'Six');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (231, 'Series Iii');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (232, 'Viper');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (233, 'Caliber');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (234, 'Nitro');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (235, 'Avenger');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (236, 'Journey');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (237, 'F355');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (238, '360');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (239, 'F430');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (240, 'F512 M');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (241, '550 Maranello');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (242, '575m Maranello');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (243, '599');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (244, '456');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (245, '456m');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (246, '612');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (247, 'F50');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (248, 'Enzo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (249, 'Superamerica');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (250, '430');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (251, '348');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (252, 'Testarossa');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (253, '512');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (254, '355');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (255, 'F40');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (256, '412');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (257, 'Mondial');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (258, '328');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (259, 'California');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (260, '458');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (261, 'Ff');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (262, 'Croma');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (263, 'Cinquecento');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (264, 'Seicento');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (265, 'Punto');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (266, 'Grande Punto');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (267, 'Panda');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (268, 'Tipo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (269, 'Coupe');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (270, 'Uno');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (271, 'Ulysse');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (272, 'Tempra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (273, 'Marea');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (274, 'Barchetta');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (275, 'Bravo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (276, 'Stilo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (277, 'Brava');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (278, 'Palio Weekend');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (279, '600');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (280, 'Multipla');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (281, 'Idea');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (282, 'Sedici');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (283, 'Linea');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (284, '500');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (285, 'Fiorino');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (286, 'Ducato');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (287, 'Doblo Cargo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (288, 'Doblo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (289, 'Strada');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (290, 'Regata');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (291, 'Talento');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (292, 'Argenta');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (293, 'Ritmo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (294, 'Punto Classic');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (295, 'Qubo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (296, 'Punto Evo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (297, '500c');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (298, 'Freemont');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (299, 'Panda Classic');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (300, '500l');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (301, 'Maverick');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (302, 'Escort');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (303, 'Focus');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (304, 'Mondeo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (305, 'Scorpio');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (306, 'Fiesta');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (307, 'Probe');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (308, 'Explorer');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (309, 'Galaxy');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (310, 'Ka');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (311, 'Puma');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (312, 'Cougar');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (313, 'Focus Cmax');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (314, 'Fusion');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (315, 'Streetka');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (316, 'Cmax');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (317, 'Smax');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (318, 'Transit');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (319, 'Courier');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (320, 'Ranger');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (321, 'Sierra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (322, 'Orion');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (323, 'Pick Up');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (324, 'Capri');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (325, 'Granada');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (326, 'Kuga');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (327, 'Grand Cmax');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (328, 'Bmax');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (329, 'Tourneo Custom');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (330, 'Exceed');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (331, 'Santamo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (332, 'Super Exceed');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (333, 'Accord');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (334, 'Civic');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (335, 'Crx');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (336, 'Prelude');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (337, 'Nsx');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (338, 'Legend');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (339, 'Crv');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (340, 'Hrv');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (341, 'Logo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (342, 'S2000');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (343, 'Stream');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (344, 'Jazz');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (345, 'Frv');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (346, 'Concerto');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (347, 'Insight');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (348, 'Crz');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (349, 'H2');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (350, 'H3');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (351, 'H3t');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (352, 'Lantra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (353, 'Sonata');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (354, 'Elantra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (355, 'Accent');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (356, 'Scoupe');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (357, 'Coupe');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (358, 'Atos');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (359, 'H1');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (360, 'Atos Prime');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (361, 'Xg');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (362, 'Trajet');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (363, 'Santa Fe');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (364, 'Terracan');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (365, 'Matrix');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (366, 'Getz');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (367, 'Tucson');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (368, 'I30');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (369, 'Pony');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (370, 'Grandeur');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (371, 'I10');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (372, 'I800');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (373, 'Sonata Fl');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (374, 'Ix55');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (375, 'I20');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (376, 'Ix35');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (377, 'Ix20');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (378, 'Genesis');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (379, 'I40');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (380, 'Veloster');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (381, 'G');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (382, 'Ex');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (383, 'Fx');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (384, 'M');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (385, 'Elba');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (386, 'Minitre');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (387, 'Trooper');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (388, 'Pick Up');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (389, 'D Max');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (390, 'Rodeo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (391, 'Dmax');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (392, 'Trroper');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (393, 'Daily');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (394, 'Massif');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (395, 'Daily');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (396, 'Duty');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (397, 'Serie Xj');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (398, 'Serie Xk');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (399, 'Xj');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (400, 'Stype');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (401, 'Xf');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (402, 'Xtype');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (403, 'Wrangler');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (404, 'Cherokee');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (405, 'Grand Cherokee');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (406, 'Commander');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (407, 'Compass');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (408, 'Wrangler Unlimited');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (409, 'Patriot');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (410, 'Sportage');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (411, 'Sephia');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (412, 'Sephia Ii');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (413, 'Pride');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (414, 'Clarus');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (415, 'Shuma');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (416, 'Carnival');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (417, 'Joice');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (418, 'Magentis');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (419, 'Carens');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (420, 'Rio');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (421, 'Cerato');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (422, 'Sorento');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (423, 'Opirus');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (424, 'Picanto');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (425, 'Ceed');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (426, 'Ceed Sporty Wagon');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (427, 'Proceed');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (428, 'K2500 Frontier');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (429, 'K2500');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (430, 'Soul');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (431, 'Venga');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (432, 'Optima');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (433, 'Ceed Sportswagon');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (434, 'Samara');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (435, 'Niva');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (436, 'Sagona');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (437, 'Stawra 2110');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (438, '214');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (439, 'Kalina');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (440, 'Serie 2100');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (441, 'Priora');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (442, 'Gallardo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (443, 'Murcielago');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (444, 'Aventador');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (445, 'Delta');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (446, 'K');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (447, 'Y10');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (448, 'Dedra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (449, 'Lybra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (450, 'Z');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (451, 'Y');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (452, 'Ypsilon');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (453, 'Thesis');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (454, 'Phedra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (455, 'Musa');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (456, 'Thema');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (457, 'Zeta');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (458, 'Kappa');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (459, 'Trevi');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (460, 'Prisma');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (461, 'A112');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (462, 'Ypsilon Elefantino');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (463, 'Voyager');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (464, 'Range Rover');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (465, 'Defender');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (466, 'Discovery');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (467, 'Freelander');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (468, 'Range Rover Sport');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (469, 'Discovery 4');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (470, 'Range Rover Evoque');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (471, 'Maxus');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (472, 'Ls400');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (473, 'Ls430');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (474, 'Gs300');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (475, 'Is200');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (476, 'Rx300');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (477, 'Gs430');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (478, 'Gs460');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (479, 'Sc430');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (480, 'Is300');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (481, 'Is250');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (482, 'Rx400h');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (483, 'Is220d');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (484, 'Rx350');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (485, 'Gs450h');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (486, 'Ls460');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (487, 'Ls600h');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (488, 'Ls');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (489, 'Gs');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (490, 'Is');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (491, 'Sc');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (492, 'Rx');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (493, 'Ct');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (494, 'Elise');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (495, 'Exige');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (496, 'Bolero Pickup');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (497, 'Goa Pickup');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (498, 'Goa');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (499, 'Cj');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (500, 'Pikup');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (501, 'Thar');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (502, 'Ghibli');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (503, 'Shamal');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (504, 'Quattroporte');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (505, '3200 Gt');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (506, 'Coupe');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (507, 'Spyder');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (508, 'Gransport');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (509, 'Granturismo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (510, '430');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (511, 'Biturbo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (512, '228');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (513, '224');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (514, 'Grancabrio');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (515, 'Maybach');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (516, 'Xedos 6');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (517, '626');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (518, '121');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (519, 'Xedos 9');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (520, '323');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (521, 'Mx3');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (522, 'Rx7');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (523, 'Mx5');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (524, 'Mazda3');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (525, 'Mpv');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (526, 'Demio');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (527, 'Premacy');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (528, 'Tribute');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (529, 'Mazda6');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (530, 'Mazda2');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (531, 'Rx8');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (532, 'Mazda5');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (533, 'Cx7');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (534, 'Serie B');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (535, 'B2500');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (536, 'Bt50');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (537, 'Mx6');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (538, '929');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (539, 'Cx5');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (540, 'Clase C');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (541, 'Clase E');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (542, 'Clase Sl');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (543, 'Clase S');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (544, 'Clase Cl');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (545, 'Clase G');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (546, 'Clase Slk');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (547, 'Clase V');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (548, 'Viano');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (549, 'Clase Clk');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (550, 'Clase A');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (551, 'Clase M');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (552, 'Vaneo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (553, 'Slklasse');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (554, 'Slr Mclaren');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (555, 'Clase Cls');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (556, 'Clase R');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (557, 'Clase Gl');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (558, 'Clase B');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (559, '100d');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (560, '140d');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (561, '180d');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (562, 'Sprinter');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (563, 'Vito');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (564, 'Transporter');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (565, '280');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (566, '220');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (567, '200');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (568, '190');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (569, '600');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (570, '400');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (571, 'Clase Sl R129');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (572, '300');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (573, '500');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (574, '420');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (575, '260');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (576, '230');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (577, 'Clase Clc');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (578, 'Clase Glk');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (579, 'Sls Amg');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (580, 'Mgf');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (581, 'Tf');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (582, 'Zr');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (583, 'Zs');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (584, 'Zt');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (585, 'Ztt');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (586, 'Mini');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (587, 'Countryman');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (588, 'Paceman');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (589, 'Montero');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (590, 'Galant');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (591, 'Colt');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (592, 'Space Wagon');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (593, 'Space Runner');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (594, 'Space Gear');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (595, '3000 Gt');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (596, 'Carisma');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (597, 'Eclipse');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (598, 'Space Star');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (599, 'Montero Sport');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (600, 'Montero Io');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (601, 'Outlander');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (602, 'Lancer');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (603, 'Grandis');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (604, 'L200');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (605, 'Canter');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (606, '300 Gt');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (607, 'Asx');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (608, 'Imiev');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (609, '44');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (610, 'Plus 8');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (611, 'Aero 8');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (612, 'V6');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (613, 'Roadster');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (614, '4');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (615, 'Plus 4');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (616, 'Terrano Ii');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (617, 'Terrano');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (618, 'Micra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (619, 'Sunny');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (620, 'Primera');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (621, 'Serena');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (622, 'Patrol');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (623, 'Maxima Qx');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (624, '200 Sx');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (625, '300 Zx');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (626, 'Patrol Gr');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (627, '100 Nx');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (628, 'Almera');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (629, 'Pathfinder');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (630, 'Almera Tino');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (631, 'Xtrail');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (632, '350z');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (633, 'Murano');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (634, 'Note');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (635, 'Qashqai');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (636, 'Tiida');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (637, 'Vanette');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (638, 'Trade');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (639, 'Vanette Cargo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (640, 'Pickup');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (641, 'Navara');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (642, 'Cabstar E');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (643, 'Cabstar');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (644, 'Maxima');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (645, 'Camion');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (646, 'Prairie');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (647, 'Bluebird');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (648, 'Np300 Pick Up');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (649, 'Qashqai2');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (650, 'Pixo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (651, 'Gtr');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (652, '370z');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (653, 'Cube');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (654, 'Juke');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (655, 'Leaf');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (656, 'Evalia');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (657, 'Astra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (658, 'Vectra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (659, 'Calibra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (660, 'Corsa');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (661, 'Omega');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (662, 'Frontera');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (663, 'Tigra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (664, 'Monterey');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (665, 'Sintra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (666, 'Zafira');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (667, 'Agila');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (668, 'Speedster');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (669, 'Signum');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (670, 'Meriva');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (671, 'Antara');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (672, 'Gt');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (673, 'Combo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (674, 'Movano');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (675, 'Vivaro');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (676, 'Kadett');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (677, 'Monza');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (678, 'Senator');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (679, 'Rekord');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (680, 'Manta');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (681, 'Ascona');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (682, 'Insignia');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (683, 'Zafira Tourer');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (684, 'Ampera');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (685, 'Mokka');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (686, 'Adam');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (687, '306');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (688, '605');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (689, '106');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (690, '205');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (691, '405');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (692, '406');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (693, '806');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (694, '807');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (695, '407');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (696, '307');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (697, '206');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (698, '607');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (699, '308');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (700, '307 Sw');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (701, '206 Sw');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (702, '407 Sw');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (703, '1007');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (704, '107');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (705, '207');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (706, '4007');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (707, 'Boxer');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (708, 'Partner');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (709, 'J5');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (710, '604');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (711, '505');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (712, '309');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (713, 'Bipper');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (714, 'Partner Origin');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (715, '3008');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (716, '5008');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (717, 'Rcz');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (718, '508');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (719, 'Ion');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (720, '208');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (721, '4008');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (722, 'Trans Sport');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (723, 'Firebird');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (724, 'Trans Am');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (725, '911');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (726, 'Boxster');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (727, 'Cayenne');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (728, 'Carrera Gt');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (729, 'Cayman');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (730, '928');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (731, '968');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (732, '944');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (733, '924');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (734, 'Panamera');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (735, '918');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (736, 'Megane');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (737, 'Safrane');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (738, 'Laguna');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (739, 'Clio');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (740, 'Twingo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (741, 'Nevada');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (742, 'Espace');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (743, 'Spider');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (744, 'Scenic');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (745, 'Grand Espace');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (746, 'Avantime');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (747, 'Vel Satis');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (748, 'Grand Scenic');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (749, 'Clio Campus');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (750, 'Modus');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (751, 'Express');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (752, 'Trafic');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (753, 'Master');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (754, 'Kangoo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (755, 'Mascott');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (756, 'Master Propulsion');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (757, 'Maxity');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (758, 'R19');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (759, 'R25');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (760, 'R5');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (761, 'R21');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (762, 'R4');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (763, 'Alpine');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (764, 'Fuego');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (765, 'R18');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (766, 'R11');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (767, 'R9');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (768, 'R6');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (769, 'Grand Modus');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (770, 'Kangoo Combi');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (771, 'Koleos');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (772, 'Fluence');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (773, 'Wind');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (774, 'Latitude');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (775, 'Grand Kangoo Combi');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (776, 'Siver Dawn');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (777, 'Silver Spur');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (778, 'Park Ward');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (779, 'Silver Seraph');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (780, 'Corniche');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (781, 'Phantom');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (782, 'Touring');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (783, 'Silvier');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (784, '800');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (785, '600');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (786, '100');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (787, '200');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (788, 'Coupe');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (789, '400');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (790, '45');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (791, 'Cabriolet');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (792, '25');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (793, 'Mini');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (794, '75');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (795, 'Streetwise');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (796, 'Sd');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (797, '900');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (798, '93');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (799, '9000');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (800, '95');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (801, '93x');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (802, '94x');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (803, '300');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (804, '350');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (805, 'Anibal');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (806, 'Anibal Pick Up');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (807, 'Ibiza');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (808, 'Cordoba');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (809, 'Toledo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (810, 'Marbella');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (811, 'Alhambra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (812, 'Arosa');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (813, 'Leon');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (814, 'Altea');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (815, 'Altea Xl');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (816, 'Altea Freetrack');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (817, 'Terra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (818, 'Inca');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (819, 'Malaga');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (820, 'Ronda');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (821, 'Exeo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (822, 'Mii');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (823, 'Felicia');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (824, 'Forman');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (825, 'Octavia');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (826, 'Octavia Tour');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (827, 'Fabia');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (828, 'Superb');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (829, 'Roomster');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (830, 'Scout');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (831, 'Pickup');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (832, 'Favorit');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (833, '130');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (834, 'S');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (835, 'Yeti');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (836, 'Citigo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (837, 'Rapid');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (838, 'Smart');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (839, 'Citycoupe');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (840, 'Fortwo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (841, 'Cabrio');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (842, 'Crossblade');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (843, 'Roadster');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (844, 'Forfour');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (845, 'Korando');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (846, 'Family');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (847, 'K4d');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (848, 'Musso');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (849, 'Korando Kj');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (850, 'Rexton');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (851, 'Rexton Ii');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (852, 'Rodius');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (853, 'Kyron');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (854, 'Actyon');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (855, 'Sports Pick Up');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (856, 'Actyon Sports Pick Up');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (857, 'Kodando');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (858, 'Legacy');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (859, 'Impreza');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (860, 'Svx');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (861, 'Justy');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (862, 'Outback');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (863, 'Forester');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (864, 'G3x Justy');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (865, 'B9 Tribeca');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (866, 'Xt');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (867, '1800');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (868, 'Tribeca');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (869, 'Wrx Sti');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (870, 'Trezia');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (871, 'Xv');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (872, 'Brz');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (873, 'Maruti');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (874, 'Swift');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (875, 'Vitara');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (876, 'Baleno');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (877, 'Samurai');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (878, 'Alto');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (879, 'Wagon R');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (880, 'Jimny');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (881, 'Grand Vitara');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (882, 'Ignis');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (883, 'Liana');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (884, 'Grand Vitara Xl7');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (885, 'Sx4');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (886, 'Splash');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (887, 'Kizashi');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (888, 'Samba');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (889, 'Tagora');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (890, 'Solara');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (891, 'Horizon');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (892, 'Telcosport');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (893, 'Telco');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (894, 'Sumo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (895, 'Safari');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (896, 'Indica');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (897, 'Indigo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (898, 'Grand Safari');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (899, 'Tl Pick Up');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (900, 'Xenon Pick Up');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (901, 'Vista');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (902, 'Xenon');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (903, 'Aria');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (904, 'Carina E');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (905, '4runner');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (906, 'Camry');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (907, 'Rav4');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (908, 'Celica');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (909, 'Supra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (910, 'Paseo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (911, 'Land Cruiser 80');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (912, 'Land Cruiser 100');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (913, 'Land Cruiser');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (914, 'Land Cruiser 90');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (915, 'Corolla');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (916, 'Auris');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (917, 'Avensis');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (918, 'Picnic');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (919, 'Yaris');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (920, 'Yaris Verso');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (921, 'Mr2');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (922, 'Previa');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (923, 'Prius');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (924, 'Avensis Verso');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (925, 'Corolla Verso');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (926, 'Corolla Sedan');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (927, 'Aygo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (928, 'Hilux');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (929, 'Dyna');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (930, 'Land Cruiser 200');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (931, 'Verso');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (932, 'Iq');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (933, 'Urban Cruiser');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (934, 'Gt86');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (935, '100');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (936, '121');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (937, '214');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (938, '110 Stawra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (939, '111 Stawra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (940, '215');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (941, '112 Stawra');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (942, 'Passat');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (943, 'Golf');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (944, 'Vento');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (945, 'Polo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (946, 'Corrado');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (947, 'Sharan');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (948, 'Lupo');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (949, 'Bora');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (950, 'Jetta');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (951, 'New Beetle');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (952, 'Phaeton');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (953, 'Touareg');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (954, 'Touran');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (955, 'Multivan');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (956, 'Caddy');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (957, 'Golf Plus');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (958, 'Fox');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (959, 'Eos');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (960, 'Caravelle');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (961, 'Tiguan');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (962, 'Transporter');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (963, 'Lt');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (964, 'Taro');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (965, 'Crafter');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (966, 'California');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (967, 'Santana');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (968, 'Scirocco');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (969, 'Passat Cc');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (970, 'Amarok');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (971, 'Beetle');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (972, 'Up');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (973, 'Cc');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (974, '440');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (975, '850');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (976, 'S70');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (977, 'V70');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (978, 'V70 Classic');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (979, '940');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (980, '480');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (981, '460');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (982, '960');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (983, 'S90');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (984, 'V90');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (985, 'Classic');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (986, 'S40');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (987, 'V40');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (988, 'V50');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (989, 'V70 Xc');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (990, 'Xc70');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (991, 'C70');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (992, 'S80');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (993, 'S60');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (994, 'Xc90');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (995, 'C30');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (996, '780');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (997, '760');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (998, '740');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (999, '240');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (1000, '360');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (1001, '340');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (1002, 'Xc60');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (1003, 'V60');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (1004, 'V40 Cross Country');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (1005, '353');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (1006, 'Mini');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (1007, 'Countryman');
INSERT INTO `modelos`(`ID`, `Nombre`) VALUES (1008, 'Paceman');
